import type { Locator, Page } from "@playwright/test";

import { ALICE_STORAGE_STATE } from "./support/auth";
import {
  DEFAULT_COLUMNS,
  addCards,
  cardLink,
  cardTitles,
  column,
  columnHeadings,
  expect,
  test,
} from "./support/boards";
import { trackServerActions } from "./support/server-actions";

// Drag and drop of cards and columns (mouse and keyboard).
//
// Isolation: every test works on a fresh board of its own (the `board`
// fixture in support/boards.ts), so tests never see each other's moves.
//
// Persistence: moves are optimistic, so each test waits for the move's Server
// Action to finish and reloads: the order after the reload is what the server
// computed and stored.
//
// Not covered here:
// - A plain click on a card opening its modal: board-view.spec.ts covers it on
//   the Demo board, where Alice is the owner and so gets the draggable cards.
// - Viewers getting a static board: the seed has no viewer and the app has no
//   way to add a board member yet, so there is no viewer to sign in as.

test.use({ storageState: ALICE_STORAGE_STATE });

/**
 * dnd-kit's live region (role="status", no accessible name, one per board).
 * Its id is generated by dnd-kit ("DndLiveRegion-<n>"), the only stable handle.
 */
function liveRegion(page: Page): Locator {
  return page.locator("[id^=DndLiveRegion]");
}

type AnnouncementLog = { __dndAnnouncements?: string[] };

/**
 * Records every text the live region shows from now on. Needed because a
 * message can be replaced right away by the next one (the region is atomic
 * and assertive), so asserting only its current text could miss it.
 */
async function recordAnnouncements(page: Page): Promise<() => Promise<string[]>> {
  await liveRegion(page).evaluate((region) => {
    const log: string[] = [];
    (window as unknown as AnnouncementLog).__dndAnnouncements = log;
    new MutationObserver(() => {
      const text = region.textContent ?? "";
      if (text && log.at(-1) !== text) log.push(text);
    }).observe(region, { childList: true, characterData: true, subtree: true });
  });
  return () =>
    page.evaluate(() => [...((window as unknown as AnnouncementLog).__dndAnnouncements ?? [])]);
}

/** Adds the cards to a column and closes the composer, once the server has them. */
/**
 * Space on the focused card link or grip, then waits for the "Picked up"
 * announcement. dnd-kit's keyboard sensor adds its keydown listener in a
 * setTimeout after activation, so an arrow pressed right away is lost: the
 * short pause covers that (there is nothing in the DOM to wait for).
 */
async function pickUp(
  page: Page,
  announcements: () => Promise<string[]>,
  message: string,
): Promise<void> {
  await page.keyboard.press("Space");
  await expect.poll(announcements).toContain(message);
  await page.waitForTimeout(100);
}

async function seedCards(
  page: Page,
  actions: ReturnType<typeof trackServerActions>,
  columnTitle: string,
  titles: string[],
): Promise<void> {
  const composer = await addCards(page, columnTitle, titles);
  await composer.press("Escape");
  await actions.settled(actions.started());
  await expect(cardTitles(page, columnTitle)).toHaveText(titles);
}

type Point = { x: number; y: number };

async function centerOf(locator: Locator): Promise<Point> {
  const box = await locator.boundingBox();
  if (!box) throw new Error("element has no bounding box");
  return { x: box.x + box.width / 2, y: box.y + box.height / 2 };
}

/**
 * Drags with the real mouse: press, move past the 5px activation distance,
 * then glide to `to` in small steps (dnd-kit needs the intermediate moves to
 * detect collisions), and release.
 */
async function mouseDrag(page: Page, from: Point, to: Point): Promise<void> {
  await page.mouse.move(from.x, from.y);
  await page.mouse.down();
  await page.mouse.move(from.x + 10, from.y + 10, { steps: 5 });
  await page.mouse.move(to.x, to.y, { steps: 20 });
  // One last nudge on the target so the final position is measured.
  await page.mouse.move(to.x + 1, to.y + 1, { steps: 2 });
  await page.mouse.up();
}

test.describe("mouse", () => {
  test("moves a card into an empty column and next to a card in another column", async ({
    boardPage: page,
  }) => {
    const actions = trackServerActions(page);
    await seedCards(page, actions, "To do", ["Alpha card", "Bravo card", "Charlie card"]);
    const before = actions.started();

    // Into the empty "In progress" column (dropped on the column itself).
    await mouseDrag(
      page,
      await centerOf(cardLink(page, "Bravo card")),
      await centerOf(column(page, "In progress")),
    );

    await expect(cardTitles(page, "To do")).toHaveText(["Alpha card", "Charlie card"]);
    await expect(cardTitles(page, "In progress")).toHaveText(["Bravo card"]);
    await expect(liveRegion(page)).toHaveText(
      "Dropped card Bravo card. Card is in column In progress, position 1 of 1.",
    );
    // A drag is not a click: the card modal stays closed.
    await expect(page.getByRole("dialog")).toHaveCount(0);
    await expect(page).not.toHaveURL(/[?&]card=/);

    // Into a column with a card: dropped in the space below "Bravo card", so after it.
    const bravo = await column(page, "In progress")
      .getByRole("listitem")
      .filter({ has: page.getByRole("link", { name: "Bravo card", exact: true }) })
      .boundingBox();
    if (!bravo) throw new Error("Bravo card has no bounding box");
    await mouseDrag(page, await centerOf(cardLink(page, "Alpha card")), {
      x: bravo.x + bravo.width / 2,
      y: bravo.y + bravo.height + 24,
    });

    await expect(cardTitles(page, "To do")).toHaveText(["Charlie card"]);
    await expect(cardTitles(page, "In progress")).toHaveText(["Bravo card", "Alpha card"]);

    await actions.settled(before + 2);
    await page.reload();
    await expect(columnHeadings(page)).toHaveText(DEFAULT_COLUMNS);
    await expect(cardTitles(page, "To do")).toHaveText(["Charlie card"]);
    await expect(cardTitles(page, "In progress")).toHaveText(["Bravo card", "Alpha card"]);
    await expect(cardTitles(page, "Done")).toHaveCount(0);
  });

  test("reorders a card within its column", async ({ boardPage: page }) => {
    const actions = trackServerActions(page);
    await seedCards(page, actions, "To do", ["Alpha card", "Bravo card", "Charlie card"]);
    const before = actions.started();

    // The last card, dragged onto the first one, takes its place at the top.
    await mouseDrag(
      page,
      await centerOf(cardLink(page, "Charlie card")),
      await centerOf(cardLink(page, "Alpha card")),
    );

    await expect(cardTitles(page, "To do")).toHaveText([
      "Charlie card",
      "Alpha card",
      "Bravo card",
    ]);
    await expect(liveRegion(page)).toHaveText(
      "Dropped card Charlie card. Card is in column To do, position 1 of 3.",
    );
    await expect(page).not.toHaveURL(/[?&]card=/);

    await actions.settled(before + 1);
    await page.reload();
    await expect(cardTitles(page, "To do")).toHaveText([
      "Charlie card",
      "Alpha card",
      "Bravo card",
    ]);
  });
});

test.describe("keyboard", () => {
  test("Space picks a card up, arrows move it across columns, Space drops it", async ({
    boardPage: page,
  }) => {
    const actions = trackServerActions(page);
    await seedCards(page, actions, "To do", ["Alpha card", "Bravo card"]);
    await seedCards(page, actions, "Done", ["Delta card"]);
    const before = actions.started();
    const announcer = liveRegion(page);
    const announcements = await recordAnnouncements(page);

    const alpha = cardLink(page, "Alpha card");
    await alpha.focus();
    await pickUp(
      page,
      announcements,
      "Picked up card Alpha card. Card is in column To do, position 1 of 2.",
    );

    // Right: into the empty "In progress" column.
    await page.keyboard.press("ArrowRight");
    await expect(announcer).toHaveText(
      "Card Alpha card is now in column In progress, position 1 of 1.",
    );

    // Right again: into "Done", next to its card.
    await page.keyboard.press("ArrowRight");
    await expect(announcer).toContainText("Card Alpha card is now in column Done, position");

    // Down: below "Delta card".
    await page.keyboard.press("ArrowDown");
    await expect(announcer).toHaveText("Card Alpha card is now in column Done, position 2 of 2.");

    await page.keyboard.press("Space");
    await expect(announcer).toHaveText(
      "Dropped card Alpha card. Card is in column Done, position 2 of 2.",
    );
    await expect(cardTitles(page, "To do")).toHaveText(["Bravo card"]);
    await expect(cardTitles(page, "In progress")).toHaveCount(0);
    await expect(cardTitles(page, "Done")).toHaveText(["Delta card", "Alpha card"]);
    // Space is not Enter: the card modal stays closed.
    await expect(page.getByRole("dialog")).toHaveCount(0);

    await actions.settled(before + 1);
    await page.reload();
    await expect(cardTitles(page, "To do")).toHaveText(["Bravo card"]);
    await expect(cardTitles(page, "In progress")).toHaveCount(0);
    await expect(cardTitles(page, "Done")).toHaveText(["Delta card", "Alpha card"]);
  });

  test("Escape cancels a move: the order is unchanged and nothing is saved", async ({
    boardPage: page,
  }) => {
    const actions = trackServerActions(page);
    await seedCards(page, actions, "To do", ["Alpha card", "Bravo card", "Charlie card"]);
    const before = actions.started();
    const announcer = liveRegion(page);
    const announcements = await recordAnnouncements(page);

    await cardLink(page, "Alpha card").focus();
    await pickUp(
      page,
      announcements,
      "Picked up card Alpha card. Card is in column To do, position 1 of 3.",
    );
    await page.keyboard.press("ArrowDown");
    await expect(announcer).toHaveText("Card Alpha card is now in column To do, position 2 of 3.");
    await page.keyboard.press("ArrowRight");
    await expect(announcer).toHaveText(
      "Card Alpha card is now in column In progress, position 1 of 1.",
    );

    await page.keyboard.press("Escape");

    await expect(announcer).toHaveText(
      "Movement cancelled. Card Alpha card is back in column To do, position 1 of 3.",
    );
    await expect(cardTitles(page, "To do")).toHaveText([
      "Alpha card",
      "Bravo card",
      "Charlie card",
    ]);
    await expect(cardTitles(page, "In progress")).toHaveCount(0);
    // Escape only cancels the drag: it does not open (or leave) anything else.
    await expect(page.getByRole("dialog")).toHaveCount(0);
    expect(actions.started()).toBe(before);

    await page.reload();
    await expect(cardTitles(page, "To do")).toHaveText([
      "Alpha card",
      "Bravo card",
      "Charlie card",
    ]);
    await expect(cardTitles(page, "In progress")).toHaveCount(0);
  });

  test("Enter on a card still opens its modal instead of picking it up", async ({
    boardPage: page,
  }) => {
    const actions = trackServerActions(page);
    await seedCards(page, actions, "To do", ["Alpha card"]);

    const announcements = await recordAnnouncements(page);
    await cardLink(page, "Alpha card").focus();
    await page.keyboard.press("Enter");

    await expect(page.getByRole("dialog", { name: "Alpha card" })).toBeVisible();
    await expect(page).toHaveURL(/[?&]card=[0-9a-f-]{36}/);
    expect(await announcements()).toEqual([]);
  });

  test("a column's grip moves the column with Space, arrows and Enter", async ({
    boardPage: page,
  }) => {
    const actions = trackServerActions(page);
    await seedCards(page, actions, "To do", ["Alpha card"]);
    const before = actions.started();
    const announcer = liveRegion(page);
    const announcements = await recordAnnouncements(page);

    const grip = column(page, "To do").getByRole("button", { name: "Move column To do" });
    await grip.focus();
    await pickUp(page, announcements, "Picked up column To do. Column is in position 1 of 3.");

    await page.keyboard.press("ArrowRight");
    await expect(announcer).toHaveText("Column To do is now in position 2 of 3.");
    await page.keyboard.press("ArrowRight");
    await expect(announcer).toHaveText("Column To do is now in position 3 of 3.");

    await page.keyboard.press("Enter");
    await expect(announcer).toHaveText("Dropped column To do. Column is in position 3 of 3.");
    await expect(columnHeadings(page)).toHaveText(["In progress", "Done", "To do"]);
    // The column's cards travel with it.
    await expect(cardTitles(page, "To do")).toHaveText(["Alpha card"]);

    await actions.settled(before + 1);
    await page.reload();
    await expect(columnHeadings(page)).toHaveText(["In progress", "Done", "To do"]);
    await expect(cardTitles(page, "To do")).toHaveText(["Alpha card"]);
  });
});
