import { z } from "zod";

/** 32 random bytes as unpadded base64url, as generated by create_board_invite. */
export const INVITE_TOKEN_LENGTH = 43;

export const inviteTokenSchema = z
  .string({ error: "This invite link is not valid." })
  .regex(/^[A-Za-z0-9_-]{43}$/, { error: "This invite link is not valid." });

/** Invites never grant "owner" (ADR 0018). */
export const INVITE_ROLES = ["editor", "viewer"] as const;
export const inviteRoleSchema = z.enum(INVITE_ROLES, { error: "Choose Editor or Viewer." });
export type InviteRole = z.infer<typeof inviteRoleSchema>;

const boardId = z.uuid({ error: "Invalid board." });

export const createInviteSchema = z.object({ boardId, role: inviteRoleSchema });
export const revokeInviteSchema = z.object({
  boardId,
  inviteId: z.uuid({ error: "Invalid invite." }),
});

/**
 * One row of get_board_invite. The generated types say every text column is a
 * non-null string, so the row is parsed instead of trusted (ADR 0018).
 */
export const invitePeekSchema = z.object({
  status: z.enum(["pending", "expired", "accepted"]),
  role: inviteRoleSchema,
  expires_at: z.string(),
  is_member: z.boolean(),
  board_id: z.uuid().nullable(),
  board_title: z.string().nullable(),
  inviter_name: z.string().nullable(),
});
export type InvitePeek = z.infer<typeof invitePeekSchema>;
