// Generates .env.local from the running local Supabase (`pnpm db:start`).
// Local keys are the Supabase CLI's development defaults, not production secrets.
import { execFileSync } from "node:child_process";
import { existsSync, writeFileSync } from "node:fs";

const target = ".env.local";
const force = process.argv.includes("--force");

if (existsSync(target) && !force) {
  console.error(`${target} already exists. Run with --force to overwrite it.`);
  process.exit(1);
}

let status;
try {
  status = JSON.parse(
    execFileSync("supabase", ["status", "-o", "json"], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }),
  );
} catch {
  console.error("Local Supabase is not running. Start it with `pnpm db:start`.");
  process.exit(1);
}

const env = {
  NEXT_PUBLIC_SUPABASE_URL: status.API_URL,
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: status.PUBLISHABLE_KEY,
  SUPABASE_SECRET_KEY: status.SECRET_KEY,
};

const missing = Object.entries(env).filter(([, value]) => !value);
if (missing.length > 0) {
  console.error(`Missing values from supabase status: ${missing.map(([key]) => key).join(", ")}`);
  process.exit(1);
}

const content = Object.entries(env)
  .map(([key, value]) => `${key}=${value}`)
  .join("\n");
writeFileSync(target, `# Generated by pnpm env:local\n${content}\n`, { mode: 0o600 });
console.log(`✔ ${target} written for local Supabase at ${env.NEXT_PUBLIC_SUPABASE_URL}`);
